# Limit battery charging threshold to protect battery lifespan
w /sys/class/power_supply/qcom-battmgr-bat/charge_control_end_threshold - - - - 80
w /sys/class/power_supply/qcom-battmgr-bat/charge_control_start_threshold - - - - 70
