#!/usr/bin/env python3
"""Generate /etc/thermald/thermal-conf.xml for the Y700 Gen4 (TB322FC / sm8750).

Policy requested by the user (2026-09-30):
  * CPU  >= 90 C  -> light throttle CPU   (cpufreq-cpu0 + cpufreq-cpu6)
  * CPU  >= 100 C -> heavy throttle CPU
  * GPU  >= 90 C  -> light throttle GPU   (devfreq-3d00000.gpu)
  * GPU  >= 100 C -> heavy throttle GPU
  * BAT  >= 42 C  -> light throttle CPU+GPU together
  * BAT  >= 45 C  -> medium throttle CPU+GPU together
  * BAT  >= 48 C  -> heavy throttle CPU+GPU together

"light"/"heavy" are absolute cooling-device TargetState values, so behaviour is
deterministic (no PID, no exponential ramp).  thermald arbitrates several active
trips on the same cooling device by picking the most throttling (largest) target
state, so the 90 C and 100 C trips compose, and the battery trips compose with
the CPU/GPU trips.

One thermal zone is emitted PER SENSOR (not one zone with many sensors).  Why:
thermald inserts a synthetic POLLING trip ~10% below each zone's lowest trip and,
when a sensor drops back below its POLLING trip, calls zone_reset() which forces
*every* cooling device of that zone to its minimum state.  In a zone holding all
16 CPU (or all 8 GPU) sensors, whichever sensor is coldest around the polling
threshold keeps wiping the target set by the genuinely hot sensor.  With a single
sensor per zone a reset only ever clears that sensor's own (inactive) trips, and
the cooling device keeps the most restrictive target from the still-hot zones.

Cooling-device state -> frequency mapping (probed on the device):
  cpufreq-cpu0   (cores 0-5, 16 states):  state N -> scaling_available_frequencies[15-N]
  cpufreq-cpu6   (cores 6-7, 16 states):  index = clamp(15-N, 0, 13)
  devfreq-3d00000.gpu (14 states):        state N -> available_frequencies[13-N]
"""

# ---------------------------------------------------------------------------
# Device inventory (must match /sys/class/thermal on the tablet)
# ---------------------------------------------------------------------------

CPU_SENSORS = [
    "cpu-0-0-0-thermal", "cpu-0-0-1-thermal",
    "cpu-0-1-0-thermal", "cpu-0-1-1-thermal",
    "cpu-0-2-0-thermal", "cpu-0-2-1-thermal",
    "cpu-0-3-0-thermal", "cpu-0-3-1-thermal",
    "cpu-0-4-0-thermal", "cpu-0-4-1-thermal",
    "cpu-0-5-0-thermal", "cpu-0-5-1-thermal",
    "cpu-1-0-0-thermal", "cpu-1-0-1-thermal",
    "cpu-1-1-0-thermal", "cpu-1-1-1-thermal",
]
GPU_SENSORS = ["gpuss%d-thermal" % i for i in range(8)]
BAT_SENSOR = "qcom-battmgr-bat"

CDEV_CPU0 = "cpufreq-cpu0"
CDEV_CPU6 = "cpufreq-cpu6"
CDEV_GPU = "devfreq-3d00000.gpu"

# Cooling-device TargetState for each trigger (see mapping above).
#   name: (cpu0, cpu6, gpu)   -- None means "do not bind this cdev"
CPU_LIGHT = (4, 4, None)     # cpu0 2.75GHz / cpu6 3.51GHz
CPU_HEAVY = (11, 11, None)   # cpu0 1.15GHz / cpu6 1.96GHz
GPU_LIGHT = (None, None, 4)  # gpu 832MHz
GPU_HEAVY = (None, None, 10) # gpu 389MHz
BAT_LIGHT = (3, 3, 2)        # cpu0 2.92GHz / cpu6 3.80GHz / gpu 967MHz
BAT_MED = (6, 6, 5)          # cpu0 2.23GHz / cpu6 3.07GHz / gpu 734MHz
BAT_HEAVY = (10, 10, 8)      # cpu0 1.36GHz / cpu6 2.25GHz / gpu 525MHz

TRIP_HYST = 2000  # 2 C, applied to every trip


def cdev_block(states):
    """Emit the <CoolingDevice> elements for a (cpu0, cpu6, gpu) target tuple."""
    out = []
    for ctype, state in ((CDEV_CPU0, states[0]),
                         (CDEV_CPU6, states[1]),
                         (CDEV_GPU, states[2])):
        if state is None:
            continue
        out.append(
            "\t\t\t\t<CoolingDevice>\n"
            "\t\t\t\t\t<type>%s</type>\n"
            "\t\t\t\t\t<TargetState>%d</TargetState>\n"
            "\t\t\t\t</CoolingDevice>\n" % (ctype, state))
    return "".join(out)


def trip(sensor, temp_mdeg, states):
    return (
        "\t\t\t<TripPoint>\n"
        "\t\t\t\t<SensorType>%s</SensorType>\n"
        "\t\t\t\t<Temperature>%d</Temperature>\n"
        "\t\t\t\t<Hyst>%d</Hyst>\n"
        "\t\t\t\t<type>passive</type>\n"
        "\t\t\t\t<ControlType>PARALLEL</ControlType>\n"
        "%s"
        "\t\t\t</TripPoint>\n" % (sensor, temp_mdeg, TRIP_HYST, cdev_block(states)))


def zone(ztype, sensor, trips):
    """One zone, one sensor, a list of (temp_mdeg, states) trips."""
    body = "".join(trip(sensor, t, st) for (t, st) in trips)
    return (
        "\t\t<ThermalZone>\n"
        "\t\t\t<Type>%s</Type>\n"
        "\t\t\t<TripPoints>\n"
        "%s"
        "\t\t\t</TripPoints>\n"
        "\t\t</ThermalZone>\n" % (ztype, body))


HEADER = """<?xml version="1.0"?>
<!--
  thermald configuration for the Lenovo Legion Y700 Gen4 (TB322FC / Qualcomm
  SM8750).  GENERATED by gen_thermal_conf.py - edit the generator, not this file.

  Policy:
    CPU >= 90 C  -> light throttle CPU    (cpufreq-cpu0 + cpufreq-cpu6)
    CPU >= 100 C -> heavy throttle CPU
    GPU >= 90 C  -> light throttle GPU    (devfreq-3d00000.gpu)
    GPU >= 100 C -> heavy throttle GPU
    BAT >= 42 C  -> light throttle CPU+GPU together
    BAT >= 45 C  -> medium throttle CPU+GPU together
    BAT >= 48 C  -> heavy throttle CPU+GPU together

  Each thermal zone holds exactly ONE sensor (see gen_thermal_conf.py for why).

  Run thermald with the exclusive-control option so it switches the kernel
  thermal zones to the user_space governor and takes over from the in-kernel
  step_wise governor; otherwise the kernel governor and thermald fight over
  cur_state.  This requires CONFIG_THERMAL_GOV_USER_SPACE=y in the kernel.

  Cooling-device TargetState values are absolute cooling states:
    cpufreq-cpu0 : 4 -> 2.75GHz   11 -> 1.15GHz   (max_state 15)
    cpufreq-cpu6 : 4 -> 3.51GHz   11 -> 1.96GHz   (max_state 15)
    devfreq-gpu  : 4 -> 832MHz    10 -> 389MHz    (max_state 13)
-->

<!-- BEGIN -->
<ThermalConfiguration>
"""


def main():
    parts = [HEADER]
    parts.append("\t<Platform>\n")
    parts.append("\t\t<Name>Lenovo Legion Y700 Gen4</Name>\n")
    parts.append("\t\t<!-- matched as a prefix against /sys/firmware/devicetree/base/model -->\n")
    parts.append("\t\t<SoCModel>Lenovo Legion Y700 Gen4</SoCModel>\n")
    parts.append("\t\t<!-- ENERGY_CONSERVE is required: with PERFORMANCE thermald only\n"
                 "\t\t     applies ACTIVE/MAX trips and ignores PASSIVE trips. -->\n")
    parts.append("\t\t<Preference>ENERGY_CONSERVE</Preference>\n")
    parts.append("\t\t<ThermalZones>\n")

    # CPU: one zone per core sensor, 90/100 C -> both cpufreq cooling devices.
    for s in CPU_SENSORS:
        parts.append(zone(s.replace("-thermal", ""), s,
                          [(90000, CPU_LIGHT), (100000, CPU_HEAVY)]))
    # GPU: one zone per GPU sensor, 90/100 C -> the GPU devfreq cooling device.
    for s in GPU_SENSORS:
        parts.append(zone(s.replace("-thermal", ""), s,
                          [(90000, GPU_LIGHT), (100000, GPU_HEAVY)]))
    # Battery: 42/45/48 C -> throttle CPU and GPU together (light/medium/heavy).
    parts.append(zone("battery", BAT_SENSOR,
                      [(42000, BAT_LIGHT), (45000, BAT_MED), (48000, BAT_HEAVY)]))

    parts.append("\t\t</ThermalZones>\n")
    parts.append("\t</Platform>\n")
    parts.append("</ThermalConfiguration>\n")
    return "".join(parts)


if __name__ == "__main__":
    import sys
    out = main()
    if len(sys.argv) > 1:
        with open(sys.argv[1], "w") as f:
            f.write(out)
        print("wrote %s (%d lines, %d trips)" %
              (sys.argv[1], out.count("\n"), out.count("<TripPoint>")))
    else:
        sys.stdout.write(out)
